apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: mongo-persistent
      labels:
        app: todolist-mongo-go
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: mongo-persistent-sa
      namespace: mongo-persistent
      labels:
        component: mongo-persistent
  - kind: SecurityContextConstraints
    apiVersion: security.openshift.io/v1
    metadata:
      name: mongo-persistent-scc
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
    fsGroup:
      type: RunAsAny
    supplementalGroups:
      type: RunAsAny
    volumes:
    - '*'
    users:
    - system:admin
    - system:serviceaccount:mongo-persistent:mongo-persistent-sa
  - apiVersion: v1
    kind: Service
    metadata:
      name: todolist
      namespace: mongo-persistent
      labels:
        app: todolist
        service: todolist
        e2e-app: "true"
    spec:
      ports:
        - name: web
          port: 8000
          targetPort: 8000
      selector:
        app: todolist
        service: todolist
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todolist
      namespace: mongo-persistent
      labels:
        app: todolist
        service: todolist
        e2e-app: "true"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: todolist
          service: todolist
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: todolist
            service: todolist
            e2e-app: "true"
          annotations:
            pre.hook.backup.velero.io/container: todolist
            pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "mongosh admin -u \"$MONGO_INITDB_ROOT_USERNAME\" -p \"$MONGO_INITDB_ROOT_PASSWORD\" --eval \"db.fsyncLock()\""]'
            post.hook.backup.velero.io/container: todolist
            post.hook.backup.velero.io/command: '["/bin/bash", "-c", "mongosh admin -u \"$MONGO_INITDB_ROOT_USERNAME\" -p \"$MONGO_INITDB_ROOT_PASSWORD\" --eval \"db.fsyncUnlock()\""]'
        spec:
          serviceAccountName: mongo-persistent-sa
          containers:
          - name: todolist
            image: quay.io/migtools/oadp-ci-todolist-mongo-go-testing:latest
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              seccompProfile:
                type: RuntimeDefault
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: changeme
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: changeme
              - name: MONGO_INITDB_DATABASE
                value: todolist
            ports:
              - containerPort: 8000
                protocol: TCP
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            startupProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 40
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 10
              periodSeconds: 5
          volumes:
          - name: mongo-data
            persistentVolumeClaim:
              claimName: mongo
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: todolist-route
      namespace: mongo-persistent
    spec:
      path: "/"
      to:
        kind: Service
        name: todolist
