apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: mysql-persistent
      labels:
        app: mysql
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: mysql-persistent-sa
      namespace: mysql-persistent
      labels:
        component: mysql-persistent
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql
      namespace: mysql-persistent
      labels:
        app: mysql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - kind: SecurityContextConstraints
    apiVersion: security.openshift.io/v1
    metadata:
      name: mysql-persistent-scc
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
    fsGroup:
      type: RunAsAny
    supplementalGroups:
      type: RunAsAny
    volumes:
    - '*'
    users:
    - system:admin
    - system:serviceaccount:mysql-persistent:mysql-persistent-sa
  - apiVersion: v1
    kind: Service
    metadata:
      name: todolist
      namespace: mysql-persistent
      labels:
        app: todolist
        service: todolist
        e2e-app: "true"
    spec:
      ports:
        - name: web
          port: 8000
          targetPort: 8000
      selector:
        app: todolist
        service: todolist
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todolist
      namespace: mysql-persistent
      labels:
        app: todolist
        service: todolist
        e2e-app: "true"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: todolist
          service: todolist
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: todolist
            service: todolist
            e2e-app: "true"
        spec:
          securityContext:
            runAsNonRoot: true
          serviceAccountName: mysql-persistent-sa
          containers:
          - name: todolist
            image: quay.io/migtools/oadp-ci-todolist-mariadb-go-testing:testing
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              seccompProfile:
                type: RuntimeDefault
            env:
              - name: MYSQL_USER
                value: changeme
              - name: MYSQL_PASSWORD
                value: changeme
              - name: MYSQL_ROOT_PASSWORD
                value: root
              - name: MYSQL_DATABASE
                value: todolist
            ports:
              - containerPort: 8000
                protocol: TCP
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/data
            startupProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 40
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8000
              initialDelaySeconds: 10
              periodSeconds: 5
          volumes:
          - name: mysql-data
            persistentVolumeClaim:
              claimName: mysql
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: todolist-route
      namespace: mysql-persistent
    spec:
      path: "/"
      to:
        kind: Service
        name: todolist
